spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iot-single?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: iot-single
      # username:
      # password:

mqtt:
  uri: tcp://127.0.0.1:1883

logging:
  level:
    root: warn

springdoc:
  api-docs:
    enabled: false

knife4j:
  enable: true
  production: true
