spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      auto-index-creation: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.entity.po,com.demo.entity.vo
  configuration:
    map-underscore-to-camel-case: true

id:
  sequence-bits: 20

mqtt:
  connection-timeout: 30
  keep-alive-interval: 60
  clean-session: false
  automatic-reconnect: true

logging:
  file:
    name: /log/iot-service-single-api.log
